***#important notice before executing thr promodel on colab

#importing dependencies

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split #random spliting of data by rows
from sklearn.feature_extraction.text import TfidfVectorizer #converting txt to umerical vectirs
from sklearn.linear_model import LogisticRegression # calling algorithms
from sklearn.metrics import accuracy_score #model evaluation

#data collection and pre porcessing

In [ ]:
# loding data from csv to pandans df
raw_mail_data =pd.read_csv("/content/mail_data.csv")

In [ ]:
print(raw_mail_data)

     Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [ ]:
# replacing the null values with null strings
mail_data = raw_mail_data.where((pd.notnull(raw_mail_data)), '')

In [ ]:
#printing the 1st 5 rows
mail_data.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
#chekinf the ni of rows and coloumns in dataframe
mail_data.shape

(5572, 2)

In [ ]:
# lable encoding : replacing the lable value with a numerical value here for example we are lablelling ham to 1 and spam as 0

mail_data.loc[mail_data['Category']=='spam','Category',]=0
mail_data.loc[mail_data['Category']=='ham','Category',]=1

ham = 1 ; spam = 0

In [ ]:
mail_data.head()

  Category                                            Message
0        1  Go until jurong point, crazy.. Available only ...
1        1                      Ok lar... Joking wif u oni...
2        0  Free entry in 2 a wkly comp to win FA Cup fina...
3        1  U dun say so early hor... U c already then say...
4        1  Nah I don't think he goes to usf, he lives aro...

spliting the data into features and targets

seprating the data into text(messages) and lables(type : spam  and ham)

In [ ]:

X = mail_data['Message']

Y = mail_data['Category']

In [ ]:
print(X)

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...
5567    This is the 2nd time we have tried 2 contact u...
5568                 Will ü b going to esplanade fr home?
5569    Pity, * was in mood for that. So...any other s...
5570    The guy did some bitching but I acted like i'd...
5571                           Rofl. Its true to its name
Name: Message, Length: 5572, dtype: object

In [ ]:
print(Y)

0       1
1       1
2       0
3       1
4       1
       ..
5567    0
5568    1
5569    1
5570    1
5571    1
Name: Category, Length: 5572, dtype: object

spliting the data into train ing and testing data

In [ ]:
X_train , X_test , Y_train , Y_test = train_test_split(X,Y,test_size=0.2,random_state=6)

In [ ]:
print(X_test.shape)
print(X_train.shape)
print(X.shape)

(1115,)
(4457,)
(5572,)

to convert the textual date of the mesagees to meaningful numerical values:  aka  FEATURE EXTRACTION *(the proces of converion is vectorization}*

In [ ]:
# transforming the text data to feature vectors that can be used as input to the LOGISTIC REGRESSION
# gives the weight score to each repeated words and will be tied to ots label
#  min _df=1 :if min score of a word is less than 1 ignore it and if it is gereater than 1 then include it
# stop_words='english' : includes a set of common words that would be ignored from weighting like: is, am ,was,,etc for a specified laguage here english
# lowerxase = 'True' : converts al the text to lower case for bwtter processing
# basicaly to my crux this fuction is the tokenizer + weighter and


feature_extraction = TfidfVectorizer(min_df = 1 , stop_words = 'english', lowercase=True)
# loaded tfidfvectorizer to a variavle feature_extracton
X_train_features = feature_extraction.fit_transform(X_train) #fit data to the vectorixer fuction
X_test_features = feature_extraction.transform(X_test) # why?

# convert Y_train and Y_test as integers

Y_train = Y_train.astype("int")
Y_test = Y_test.astype("int")

In [ ]:
print(X_train_features)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 34851 stored elements and shape (4457, 7468)>
  Coords	Values
  (0, 7344)	0.3111122722485824
  (0, 4092)	0.4038517407872365
  (0, 6117)	0.3916954919324698
  (0, 3820)	0.18217298926959188
  (0, 1181)	0.34228611699929196
  (0, 6236)	0.3353532901828152
  (0, 7306)	0.3150255524780843
  (0, 2099)	0.19546796194192692
  (0, 3051)	0.2904451038668212
  (0, 6627)	0.2114682817750452
  (0, 4367)	0.2394847355385325
  (1, 3735)	0.3471924369844418
  (1, 6020)	0.6067564321041813
  (1, 6427)	0.7150552732488648
  (2, 3295)	0.3593319052094108
  (2, 3521)	0.6412099815361633
  (2, 5989)	0.47944256250199996
  (2, 3416)	0.47944256250199996
  (3, 3066)	0.3663986748734537
  (3, 847)	0.2810085229171852
  (3, 1412)	0.298929307826049
  (3, 2704)	0.28316495517304113
  (3, 6715)	0.20077616657182917
  (3, 1276)	0.25843100404716596
  (3, 3363)	0.21768085859618921
  :	:
  (4454, 2361)	0.29267754535980867
  (4454, 6141)	0.36102121953248634
  (4454, 3530)	0.35002034512047997
  (4454, 5834)	0.3841921822068188
  (4454, 844)	0.429364893705164
  (4454, 6088)	0.429364893705164
  (4455, 2813)	0.24399282993848895
  (4455, 6960)	0.35402013951810546
  (4455, 6859)	0.13756747763344182
  (4455, 2877)	0.1264814239343418
  (4455, 6114)	0.17170636203341738
  (4455, 4285)	0.15912993035670953
  (4455, 6247)	0.18069958810199524
  (4455, 4912)	0.22695945982859717
  (4455, 5958)	0.2193100479228728
  (4455, 2364)	0.2193100479228728
  (4455, 6241)	0.25274918620951214
  (4455, 1590)	0.24399282993848895
  (4455, 2805)	0.26509057721732027
  (4455, 3374)	0.5301811544346405
  (4455, 1022)	0.26509057721732027
  (4456, 2330)	0.3662556032529528
  (4456, 7355)	0.5298602380811525
  (4456, 1556)	0.5059359341843799
  (4456, 6638)	0.5737018316925427

In [ ]:
print(X_test_features)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 7642 stored elements and shape (1115, 7468)>
  Coords	Values
  (0, 1781)	0.5015482825837323
  (0, 2606)	0.5195477272827022
  (0, 4616)	0.30886565536780447
  (0, 5751)	0.3977976932309427
  (0, 7208)	0.3501127693746348
  (0, 7321)	0.31984297745592105
  (1, 2059)	0.4858808073838929
  (1, 2565)	0.6574151200440106
  (1, 6964)	0.5759559019174085
  (2, 1146)	0.19909148512830543
  (2, 6663)	0.9799809082576076
  (3, 469)	0.29454895181741475
  (3, 532)	0.3969812351082703
  (3, 793)	0.2699620503128647
  (3, 1558)	0.2179490203330411
  (3, 1667)	0.23517066269285092
  (3, 1945)	0.21058376118830086
  (3, 4145)	0.29454895181741475
  (3, 4342)	0.1962013457992145
  (3, 4429)	0.21532030674500693
  (3, 4588)	0.2272554483323079
  (3, 4593)	0.2222978964477476
  (3, 5090)	0.27642925134140806
  (3, 6237)	0.28434446570195104
  (3, 6958)	0.29454895181741475
  :	:
  (1111, 7304)	0.19081520669075766
  (1112, 650)	0.30404891390785743
  (1112, 2597)	0.2798505919102697
  (1112, 2637)	0.2898938029588927
  (1112, 2811)	0.30404891390785743
  (1112, 3596)	0.2478621502125277
  (1112, 4397)	0.16511504703240312
  (1112, 4460)	0.2478621502125277
  (1112, 5235)	0.30404891390785743
  (1112, 6114)	0.1969407341270026
  (1112, 6884)	0.18834803197369415
  (1112, 6960)	0.1353492581691499
  (1112, 7062)	0.2414971589637174
  (1112, 7255)	0.3742021703323459
  (1112, 7265)	0.23870280407320435
  (1112, 7304)	0.17846386812109033
  (1112, 7368)	0.1744051453812877
  (1113, 1837)	0.4061436411102326
  (1113, 3072)	0.5135416124948912
  (1113, 3166)	0.5052818317154745
  (1113, 4157)	0.5621500027218043
  (1114, 3143)	0.48394922991047784
  (1114, 3920)	0.6683569994991432
  (1114, 4116)	0.48394922991047784
  (1114, 7419)	0.29135065978750274

#TRAINING THE MACHINE LEARNING MODEL

LOGISTIC REGRESSION

In [ ]:
#loding the regression model to the variable model
model = LogisticRegression()

In [ ]:
# training the logistic regression model with the trainign data
model.fit(X_train_features,Y_train)

LogisticRegression()

# EVALUATING THE MODEL

1ST WE ARE TESTING THE MODEL ON TRAINIG DATA ITSELF

In [ ]:
#PREDICTION ON TRAINING DATA  (here basically the model will try to evsluate wheter the mail is - 0 or 1 ie spam or ham mail respectively)

prediction_on_training_data = model.predict(X_train_features)

# bASICALLY WE TRY TO COMPARE THE ACTUAL VALUE OF 0 AND 1 TO WHAT THE MODEL PREDICTED AND GIVE US A SCORE in between 0 and 1
accuracy_on_training_data = accuracy_score(Y_train , prediction_on_training_data )

In [ ]:
print(accuracy_on_training_data)

0.9665694413282477

In [ ]:
print(f'ACCURACY ON TRAINING DATA :{accuracy_on_training_data*100}%')

ACCURACY ON TRAINING DATA :96.65694413282478%

2ND WE ARE TESTING WITH TEST DATA

In [ ]:
#PREDICTION ON Testing DATA  (here basically the model will try to evsluate wheter the mail is - 0 or 1 ie spam or ham mail respectively)

prediction_on_testing_data = model.predict(X_test_features)

# bASICALLY WE TRY TO COMPARE THE ACTUAL VALUE OF 0 AND 1 TO WHAT THE MODEL PREDICTED AND GIVE US A SCORE in between 0 and 1
accuracy_on_testing_data = accuracy_score(Y_test , prediction_on_testing_data )

In [ ]:
print(accuracy_on_testing_data)

0.9766816143497757

In [ ]:
print(f'ACCURACY ON TESTING DATA :{accuracy_on_testing_data*100}%')

ACCURACY ON TESTING DATA :97.66816143497758%

the reason of using traingin data for testigna 1st is the case of overfitting and under fitting

overfitting:model performs verywell on training data fut performs poorly on testing data

under fitting : model performs overwhelming on traing dATA but performs very well on testing data

***but for this to be true the diffrece between the acuracy must be significant loke 98 and 60 not 96 and 97***

#BUILDING A PREDICTIVE SYSTEM
IF YOU TYPE A MEW MAIL IT WILL TELL IF IT IS A SPAM OR HAM

In [ ]:
INPUT_MAIL= [
    "Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...",
    "WINNER!! As a valued network customer you have been selected to receivea £900 prize reward! To claim call 09061701461. Claim code KL341. Valid 12 hours only."
]

# CONVERT TEXT TO FEATURE VECTOR FOR  FEATURE EXTRACTION
INPUT_DATA_FEATURES=feature_extraction.transform(INPUT_MAIL)

#MAKING PREDICTION(fit() FOR TRAINING AND predict() FOR PREDICTION)
PREDICTION=model.predict(INPUT_DATA_FEATURES)

#printing the type as ham or spam (1 and 0 respectively)
print('spam'if PREDICTION[0] == 0 else 'ham','spam'if PREDICTION[1] == 0 else 'ham')

ham spam